Check for and source bootstrap script
Any valid ZSH code can be placed in a file named `bootstrap` in
`tests/_support` (or wherever the support dir is defined). This will be
sourced into the environment prior to any tests being run. Useful for
setting up paths, autoloading functions etc.

Fix #21

diff --git a/zunit b/zunit
--- a/zunit
+++ b/zunit
@@ -937,6 +937,20 @@ function _zunit_run() {
     echo 'TAP version 13' >! $logfile_text
   fi
 
+  if [[ -n $zunit_config_directories_support ]]; then
+    local support="$zunit_config_directories_support"
+    if [[ ! -d $support ]]; then
+      echo $(color red "Support directory at $support is missing")
+      exit 1
+    fi
+
+    if [[ -f "$support/bootstrap" ]]; then
+      source "$support/bootstrap"
+      echo "$(color green '✔') Sourced bootstrap script $support/bootstrap"
+      which crash
+    fi
+  fi
+
   arguments=("$@")
   testfiles=()
 
